### ISSUE TITLE
Put the C and Fortran bindings into separate packages

### ISSUE THREAD

**Issue by astraw** [blas-lapack-rs/lapack-sys#7]
There are lapack bindings (notably Apple's Accelerate.framework) which provide lapack but not lapacke. I think it makes sense to separate the lapacke extern declarations from the `lapack-sys` crate and their rust wrappers in the `lapack` crate into new crates named `lapacke-sys` and `lapacke`.

This is related to #6.

**Comment by IvanUkhov** [comment]
I agree with you. Here is [`lapacke-sys`](https://crates.io/crates/lapacke-sys) and [`lapacke`](https://crates.io/crates/lapacke), and there is a pair of crates for CBLAS too. The next step is to remove LAPACKE from `lapack-sys` and `lapack` and to remove `CBLAS` from `blas-sys` and `blas`.

**Comment by IvanUkhov** [comment]
[Here](https://github.com/stainless-steel/blas/wiki/Usage-of-the-BLAS%E2%80%93LAPACK-family-of-crates) is a page that explains what to do, and it is supposed to be linked to from every relevant crate.

What does everybody think about it?

/cc @cmr @bluss

**Comment by bluss** [comment]
@IvanUkhov It looks good. I'll try it out when I have time.

I'd like to have written something that splits use cases, so that we have something like the below. (Since I haven't tried it out, I don't know if the advice is correct yet.)

### If writing a library

- Depend on wrapper/binding

### If writing an end user project
(end user of BLAS/LAPACK)

- Depend on wrapper/binding and implementation
